// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Group struct {
	ID         int64         `json:"id"`
	Name       string        `json:"name"`
	WordsCount sql.NullInt64 `json:"words_count"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type StudyActivity struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	Description  sql.NullString `json:"description"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type StudySession struct {
	ID              int64        `json:"id"`
	GroupID         int64        `json:"group_id"`
	StudyActivityID int64        `json:"study_activity_id"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Word struct {
	ID        int64        `json:"id"`
	Italian   string       `json:"italian"`
	English   string       `json:"english"`
	Parts     interface{}  `json:"parts"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type WordReviewItem struct {
	ID             int64        `json:"id"`
	WordID         int64        `json:"word_id"`
	StudySessionID int64        `json:"study_session_id"`
	Correct        bool         `json:"correct"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type WordsGroup struct {
	ID        int64        `json:"id"`
	WordID    int64        `json:"word_id"`
	GroupID   int64        `json:"group_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}
