// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: word_reviews.sql

package db

import (
	"context"
)

const getWordReviewsBySessionID = `-- name: GetWordReviewsBySessionID :many
SELECT id, word_id, study_session_id, correct, created_at FROM word_review_items
WHERE study_session_id = ?
`

func (q *Queries) GetWordReviewsBySessionID(ctx context.Context, studySessionID int64) ([]WordReviewItem, error) {
	rows, err := q.db.QueryContext(ctx, getWordReviewsBySessionID, studySessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WordReviewItem{}
	for rows.Next() {
		var i WordReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.WordID,
			&i.StudySessionID,
			&i.Correct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
