// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dashboard/last_study_session": {
            "get": {
                "description": "Returns information about the most recent study session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get last study session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardLastStudySession"
                        }
                    }
                }
            }
        },
        "/api/dashboard/quick-stats": {
            "get": {
                "description": "Returns quick overview statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get quick stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardQuickStats"
                        }
                    }
                }
            }
        },
        "/api/dashboard/study_progress": {
            "get": {
                "description": "Returns study progress statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get study progress",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardStudyProgress"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DashboardLastStudySession": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "study_activity_id": {
                    "type": "integer"
                }
            }
        },
        "models.DashboardQuickStats": {
            "type": "object",
            "properties": {
                "study_streak_days": {
                    "type": "integer"
                },
                "success_rate": {
                    "type": "number"
                },
                "total_active_groups": {
                    "type": "integer"
                },
                "total_study_sessions": {
                    "type": "integer"
                }
            }
        },
        "models.DashboardStudyProgress": {
            "type": "object",
            "properties": {
                "total_available_words": {
                    "type": "integer"
                },
                "total_words_studied": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Italian Language Learning Portal API",
	Description:      "API for the Italian Language Learning Portal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
