// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dashboard/last_study_session": {
            "get": {
                "description": "Returns information about the most recent study session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get last study session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardLastStudySession"
                        }
                    }
                }
            }
        },
        "/api/dashboard/quick-stats": {
            "get": {
                "description": "Returns quick overview statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get quick stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardQuickStats"
                        }
                    }
                }
            }
        },
        "/api/dashboard/study_progress": {
            "get": {
                "description": "Returns study progress statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get study progress",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardStudyProgress"
                        }
                    }
                }
            }
        },
        "/api/study_activities/{id}": {
            "get": {
                "description": "Returns details about a specific study activity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "study_activities"
                ],
                "summary": "Get study activity details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Study Activity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StudyActivityResponse"
                        }
                    }
                }
            }
        },
        "/api/study_activities/{id}/study_sessions": {
            "get": {
                "description": "Returns a list of study sessions for a specific activity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "study_activities"
                ],
                "summary": "Get study sessions for an activity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Study Activity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StudySessionsListResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DashboardLastStudySession": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "study_activity_id": {
                    "type": "integer"
                }
            }
        },
        "models.DashboardQuickStats": {
            "type": "object",
            "properties": {
                "study_streak_days": {
                    "type": "integer"
                },
                "success_rate": {
                    "type": "number"
                },
                "total_active_groups": {
                    "type": "integer"
                },
                "total_study_sessions": {
                    "type": "integer"
                }
            }
        },
        "models.DashboardStudyProgress": {
            "type": "object",
            "properties": {
                "total_available_words": {
                    "type": "integer"
                },
                "total_words_studied": {
                    "type": "integer"
                }
            }
        },
        "models.StudyActivityResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                }
            }
        },
        "models.StudySessionResponse": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string"
                },
                "correct_count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "words_count": {
                    "type": "integer"
                }
            }
        },
        "models.StudySessionsListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.StudySessionResponse"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Italian Language Learning Portal API",
	Description:      "API for the Italian Language Learning Portal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
