basePath: /
definitions:
  models.DashboardLastStudySession:
    properties:
      created_at:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
      id:
        type: integer
      study_activity_id:
        type: integer
    type: object
  models.DashboardQuickStats:
    properties:
      study_streak_days:
        type: integer
      success_rate:
        type: number
      total_active_groups:
        type: integer
      total_study_sessions:
        type: integer
    type: object
  models.DashboardStudyProgress:
    properties:
      total_available_words:
        type: integer
      total_words_studied:
        type: integer
    type: object
  models.GroupDetailResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      stats:
        $ref: '#/definitions/models.GroupStats'
    type: object
  models.GroupListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.GroupResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.GroupResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      word_count:
        type: integer
    type: object
  models.GroupStats:
    properties:
      total_word_count:
        type: integer
    type: object
  models.GroupStudySessionsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.StudySessionResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.GroupWordsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.WordResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.LaunchStudyActivityRequest:
    properties:
      group_id:
        type: integer
    required:
    - group_id
    type: object
  models.LaunchStudyActivityResponse:
    properties:
      created_at:
        type: string
      group_id:
        type: integer
      study_activity_id:
        type: integer
      study_session_id:
        type: integer
    type: object
  models.PaginationResponse:
    properties:
      current_page:
        type: integer
      items_per_page:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  models.StudyActivityListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.StudyActivityResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.StudyActivityResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      launch_url:
        type: string
      name:
        type: string
      thumbnail_url:
        type: string
    type: object
  models.StudySessionDetailResponse:
    properties:
      activity_name:
        type: string
      created_at:
        type: string
      group_name:
        type: string
      id:
        type: integer
      review_items:
        items:
          $ref: '#/definitions/models.WordReviewItem'
        type: array
      stats:
        $ref: '#/definitions/models.StudySessionStats'
    type: object
  models.StudySessionListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.StudySessionDetailResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.StudySessionResponse:
    properties:
      activity_name:
        type: string
      correct_count:
        type: integer
      created_at:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
      id:
        type: integer
      words_count:
        type: integer
    type: object
  models.StudySessionStats:
    properties:
      average_time:
        type: number
      correct_words:
        type: integer
      success_rate:
        type: number
      total_duration:
        type: number
      total_words:
        type: integer
    type: object
  models.StudySessionWordsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.WordResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.StudySessionsListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.StudySessionResponse'
        type: array
    type: object
  models.WordListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.WordResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.WordResponse:
    properties:
      correct_count:
        type: integer
      english:
        type: string
      id:
        type: integer
      italian:
        type: string
      parts:
        additionalProperties: true
        type: object
      wrong_count:
        type: integer
    type: object
  models.WordReviewItem:
    properties:
      correct:
        type: boolean
      created_at:
        type: string
      id:
        type: integer
      study_session_id:
        type: integer
      word_id:
        type: integer
    type: object
  models.WordReviewRequest:
    properties:
      correct:
        type: boolean
    required:
    - correct
    type: object
  models.WordReviewResponse:
    properties:
      success:
        type: boolean
      word_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for the Italian Language Learning Portal
  title: Italian Language Learning Portal API
  version: "1.0"
paths:
  /api/dashboard/last_study_session:
    get:
      consumes:
      - application/json
      description: Returns information about the most recent study session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DashboardLastStudySession'
      summary: Get last study session
      tags:
      - dashboard
  /api/dashboard/quick-stats:
    get:
      consumes:
      - application/json
      description: Returns quick overview statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DashboardQuickStats'
      summary: Get quick stats
      tags:
      - dashboard
  /api/dashboard/study_progress:
    get:
      consumes:
      - application/json
      description: Returns study progress statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DashboardStudyProgress'
      summary: Get study progress
      tags:
      - dashboard
  /api/full_reset:
    post:
      consumes:
      - application/json
      description: Drops all tables and recreates them with seed data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Full system reset
      tags:
      - settings
  /api/groups:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of groups
      parameters:
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupListResponse'
      summary: Get all groups
      tags:
      - groups
  /api/groups/{id}:
    get:
      consumes:
      - application/json
      description: Returns details about a specific group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupDetailResponse'
      summary: Get group by ID
      tags:
      - groups
  /api/groups/{id}/study_sessions:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of study sessions for a specific group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupStudySessionsResponse'
      summary: Get study sessions for a group
      tags:
      - groups
  /api/groups/{id}/words:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of words in a specific group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupWordsResponse'
      summary: Get words in a group
      tags:
      - groups
  /api/reset_history:
    post:
      consumes:
      - application/json
      description: Deletes all study sessions and word review items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reset study history
      tags:
      - settings
  /api/study_activities:
    get:
      consumes:
      - application/json
      description: Returns a list of available study activities
      parameters:
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StudyActivityListResponse'
      summary: Get all study activities
      tags:
      - study_activities
  /api/study_activities/{id}:
    get:
      consumes:
      - application/json
      description: Returns details about a specific study activity
      parameters:
      - description: Study Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StudyActivityResponse'
      summary: Get study activity details
      tags:
      - study_activities
  /api/study_activities/{id}/launch:
    post:
      consumes:
      - application/json
      - application/json
      description: |-
        Returns a list of study sessions for a specific activity
        Launches a new study activity session for a specific group
      parameters:
      - description: Study Activity ID
        in: path
        name: id
        required: true
        type: integer
      - description: Study Activity ID
        in: path
        name: id
        required: true
        type: integer
      - description: Launch request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LaunchStudyActivityRequest'
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LaunchStudyActivityResponse'
      summary: Launch a new study activity session
      tags:
      - study_activities
      - study_activities
  /api/study_activities/{id}/study_sessions:
    get:
      consumes:
      - application/json
      - application/json
      description: |-
        Returns a list of study sessions for a specific activity
        Launches a new study activity session for a specific group
      parameters:
      - description: Study Activity ID
        in: path
        name: id
        required: true
        type: integer
      - description: Study Activity ID
        in: path
        name: id
        required: true
        type: integer
      - description: Launch request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LaunchStudyActivityRequest'
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LaunchStudyActivityResponse'
      summary: Launch a new study activity session
      tags:
      - study_activities
      - study_activities
  /api/study_sessions:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of all study sessions with activity name,
        group name, and review items
      parameters:
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StudySessionListResponse'
      summary: Get all study sessions
      tags:
      - study_sessions
  /api/study_sessions/{id}/words:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of words reviewed in a specific study
        session
      parameters:
      - description: Study Session ID
        in: path
        name: id
        required: true
        type: integer
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StudySessionWordsResponse'
      summary: Get words for a study session
      tags:
      - study_sessions
  /api/study_sessions/{id}/words/{word_id}/review:
    post:
      consumes:
      - application/json
      description: Records whether a word was correctly or incorrectly reviewed in
        a study session
      parameters:
      - description: Study Session ID
        in: path
        name: id
        required: true
        type: integer
      - description: Word ID
        in: path
        name: word_id
        required: true
        type: integer
      - description: Review request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.WordReviewRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WordReviewResponse'
      summary: Review a word in a study session
      tags:
      - study_sessions
  /api/words:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of words
      parameters:
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WordListResponse'
      summary: Get all words
      tags:
      - words
  /api/words/{id}:
    get:
      consumes:
      - application/json
      description: Returns details about a specific word
      parameters:
      - description: Word ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WordResponse'
      summary: Get word by ID
      tags:
      - words
schemes:
- http
- https
swagger: "2.0"
