basePath: /
definitions:
  models.DashboardLastStudySession:
    properties:
      created_at:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
      id:
        type: integer
      study_activity_id:
        type: integer
    type: object
  models.DashboardQuickStats:
    properties:
      study_streak_days:
        type: integer
      success_rate:
        type: number
      total_active_groups:
        type: integer
      total_study_sessions:
        type: integer
    type: object
  models.DashboardStudyProgress:
    properties:
      total_available_words:
        type: integer
      total_words_studied:
        type: integer
    type: object
  models.GroupDetailResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      stats:
        $ref: '#/definitions/models.GroupStats'
    type: object
  models.GroupListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.GroupResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.GroupResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      word_count:
        type: integer
    type: object
  models.GroupStats:
    properties:
      total_word_count:
        type: integer
    type: object
  models.GroupStudySessionsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.StudySessionResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.GroupWordsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.WordResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.PaginationResponse:
    properties:
      current_page:
        type: integer
      items_per_page:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  models.StudyActivityResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      thumbnail_url:
        type: string
    type: object
  models.StudySessionResponse:
    properties:
      activity_name:
        type: string
      correct_count:
        type: integer
      created_at:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
      id:
        type: integer
      words_count:
        type: integer
    type: object
  models.StudySessionsListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.StudySessionResponse'
        type: array
    type: object
  models.WordListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.WordResponse'
        type: array
      pagination:
        $ref: '#/definitions/models.PaginationResponse'
    type: object
  models.WordResponse:
    properties:
      correct_count:
        type: integer
      english:
        type: string
      id:
        type: integer
      italian:
        type: string
      parts:
        items:
          type: string
        type: array
      wrong_count:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for the Italian Language Learning Portal
  title: Italian Language Learning Portal API
  version: "1.0"
paths:
  /api/dashboard/last_study_session:
    get:
      consumes:
      - application/json
      description: Returns information about the most recent study session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DashboardLastStudySession'
      summary: Get last study session
      tags:
      - dashboard
  /api/dashboard/quick-stats:
    get:
      consumes:
      - application/json
      description: Returns quick overview statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DashboardQuickStats'
      summary: Get quick stats
      tags:
      - dashboard
  /api/dashboard/study_progress:
    get:
      consumes:
      - application/json
      description: Returns study progress statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DashboardStudyProgress'
      summary: Get study progress
      tags:
      - dashboard
  /api/groups:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of groups
      parameters:
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupListResponse'
      summary: Get all groups
      tags:
      - groups
  /api/groups/{id}:
    get:
      consumes:
      - application/json
      description: Returns details about a specific group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupDetailResponse'
      summary: Get group by ID
      tags:
      - groups
  /api/groups/{id}/study_sessions:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of study sessions for a specific group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupStudySessionsResponse'
      summary: Get study sessions for a group
      tags:
      - groups
  /api/groups/{id}/words:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of words in a specific group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupWordsResponse'
      summary: Get words in a group
      tags:
      - groups
  /api/study_activities/{id}:
    get:
      consumes:
      - application/json
      description: Returns details about a specific study activity
      parameters:
      - description: Study Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StudyActivityResponse'
      summary: Get study activity details
      tags:
      - study_activities
  /api/study_activities/{id}/study_sessions:
    get:
      consumes:
      - application/json
      description: Returns a list of study sessions for a specific activity
      parameters:
      - description: Study Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StudySessionsListResponse'
      summary: Get study sessions for an activity
      tags:
      - study_activities
  /api/words:
    get:
      consumes:
      - application/json
      description: Returns a paginated list of words
      parameters:
      - default: 100
        description: Number of items per page
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WordListResponse'
      summary: Get all words
      tags:
      - words
  /api/words/{id}:
    get:
      consumes:
      - application/json
      description: Returns details about a specific word
      parameters:
      - description: Word ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WordResponse'
      summary: Get word by ID
      tags:
      - words
schemes:
- http
- https
swagger: "2.0"
