# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  textgen:
    image: ${REGISTRY:-opea}/llm-textgen:${TAG:-latest}
    container_name: llm-textgen-server
    ports:
      - ${TEXTGEN_PORT:-9000}:9000
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_ENDPOINT: ${LLM_ENDPOINT}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      LOGFLAG: ${LOGFLAG:-False}
    restart: unless-stopped

  textgen-service-ollama:
    extends: textgen
    container_name: textgen-service-ollama
    environment:
      LLM_COMPONENT_NAME: ${LLM_COMPONENT_NAME:-OpeaTextGenService}

networks:
  default:
    driver: bridge